version: '3.0'

# docker network create grpc_net --driver bridge
networks:
  net:
    name: grpc_net
    external: true

services:
  generator:
    build:
      context: .
    image: generator-app-grpc:1.0
    container_name: generator-app-grpc
    networks:
      - net
    env_file:
      - .env
    ports:
      - '8081:8081'