version: '3.0'

# docker network create grpc_net --driver bridge
networks:
  net:
    name: grpc_net
    external: true

volumes:
  meteo-redis-data:
    driver: local

services:
  redis:
    image: redis:7.2-rc-alpine
    container_name: redis-grpc-meteo
    networks:
      - net
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - meteo-redis-data:/data

  appstore:
    build:
      context: .
    container_name: meteo-store
    depends_on:
      - redis
    networks:
      - net
    env_file:
      - .env
    ports:
      - '8083:8083'

