version: '3.0'

# docker network create grpc_net --driver bridge
networks:
  net:
    name: grpc_net
    external: true

volumes:
  meteo-db-data:
    driver: local


services:
  dbase:
    image: 'postgres:15.3-alpine'
    container_name: server-db-grpc
    networks:
      - net
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - meteo-db-data:/var/lib/postgresql/data

  server:
    build:
      context: .
    image: server-app-grpc:1.0
    container_name: server-app-grpc
    depends_on:
      - dbase
    networks:
      - net
    env_file:
      - .env
    ports:
      - '8082:8082'